# [ÖNEMLİ!] Worker'ların master'a nasıl erişeceğini bildir:
spark.master                  spark://spark-master:7077

# Görev geçmişini History Server'da görmek istersek gerekli ayarlar:
spark.eventLog.enabled        true
spark.eventLog.dir            file:///opt/spark-events
